version: "3"

services:
  sqlite3:
    image: nouchka/sqlite3:latest
    stdin_open: true
    tty: true
    volumes:
      - .:/data
    networks:
      - default


  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python tutorial/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - sqlite3